import turtle
t=turtle.Turtle()
t2=turtle.Turtle()
t3=turtle.Turtle()
t4=turtle.Turtle()
t5=turtle.Turtle()
t6=turtle.Turtle()
t7=turtle.Turtle()
t8=turtle.Turtle()
t9=turtle.Turtle()
t10=turtle.Turtle()
t11=turtle.Turtle()
t12=turtle.Turtle()
t13=turtle.Turtle()
t14=turtle.Turtle()
screen = turtle.Screen()
screen.screensize(800,800)


screen.bgcolor('white')
t.penup()
t.hideturtle()
t2.penup()
t2.hideturtle()

t2.goto(0, 0)
turtle.addshape("base.gif")
t2.shape("base.gif")
turtle.addshape("cfb.gif")
t3.shape("cfb.gif")
t3.penup()
t3.goto(0,200)
a = t2.stamp()
t.goto(0, 150)
t.write("Luca Villani's Faves", font=("Arial", 24, "bold"), align="center")
t.goto(0, -150)
t.write("By Luca Villani", font=("Arial", 24, "bold"), align="center")
t.goto(200,200)
t.pendown()
t.fillcolor('yellow')
t.begin_fill()
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.end_fill()
enter = input("Press enter to continue")
t2.clearstamps()
t3.hideturtle()
t.clear()
t2.clear()
t3.clear()


t.penup()
t.goto(0,0)
t.write("Pizza", font=("Arial", 24, "bold"), align="center")
t.goto(0,-40)
t.write("Pasta", font=("Arial", 24, "bold"), align="center")
t.goto(0,-80)
t.write("Burger", font=("Arial", 24, "bold"), align="center")

screen.bgcolor('hotpink')
t.goto(-200,-200)
t.pendown()
t.fillcolor('gold3')
t.begin_fill()
t.forward(93)
t.left(135)
t.forward(90)
t.left(110)
t.forward(70)
t.left(135)
t.end_fill()

t.penup()
t4.penup()
t4.goto(-200,200)
turtle.addshape("pizza.gif")
t4.shape("pizza.gif")
t.goto(0,-10)
turtle.addshape("pasta.gif")
t5.shape("pasta.gif")
t5.penup()
t5.goto(200,-200)
t.goto(0,-20)
turtle.addshape("brgr.gif")
t6.shape("brgr.gif")
t6.penup()
t6.goto(220,220)
t.penup()
t.goto(0,150)
t.write("Favorite Foods ", font=("Arial", 24, "bold"), align="center")

enter = input("Press enter to continue")
t4.hideturtle()
t5.hideturtle()
t6.hideturtle()
t.clear()

t.goto(0,0)
t.write("Watching Football ", font=("Arial", 24, "bold"), align="center")
t.goto(0,-40)
t.write("Playing Video Games ", font=("Arial", 24, "bold"), align="center")
t.goto(0,-80)
t.write("Watching/Playing Baseball ", font=("Arial", 24, "bold"), align="center")
t.goto(-40,-120)
t.write("Watching March Madness ", font=("Arial", 24, "bold"), align="center")
screen.bgcolor('blue')
turtle.addshape("nfl.gif")
t7.shape("nfl.gif")
t7.penup()
t7.goto(210,210)
t.goto(200,0)
t.pendown()
t.fillcolor('red')
t.begin_fill()
t.circle(45)
t.end_fill()
t.penup()

turtle.addshape("vg.gif")
t8.shape("vg.gif")
t8.penup()
t8.goto(-210,210)

turtle.addshape("plr.gif")
t9.shape("plr.gif")
t9.penup()
t9.goto(210,-210)

turtle.addshape("mm.gif")
t10.shape("mm.gif")
t10.penup()
t10.goto(-210,-210)

enter = input("Press enter to continue")
t.clear()
t7.hideturtle()
t8.hideturtle()
t9.hideturtle()
t10.hideturtle()

t.goto(0,200)
t.write("Favorite Movie ", font=("Arial", 24, "bold"), align="center")
screen.bgcolor('silver')

t.goto(210,0)
t.pendown()
t.fillcolor('cornflower blue')
t.begin_fill()
t.forward(90)
t.left(90)
t.forward(70)
t.left(90)
t.forward(90)
t.left(90)
t.forward(70)
t.end_fill()
turtle.addshape("aeg.gif")
t11.shape("aeg.gif")
t13.penup()
t13.goto(-250,0)
turtle.addshape("ha.gif")
t13.shape("ha.gif")
t11.penup()
t.penup()
t.goto(0,-200)
t.write("Avengers: Endgame ", font=("Arial", 24, "bold"), align="center")
t.goto(0,-240)
t.write("Home Alone ", font=("Arial", 24, "bold"), align="center")

enter = input("Press enter to continue")
t11.hideturtle()
t13.hideturtle()
t.clear()

t.penup()
t.fillcolor('black')
t.begin_fill()
t.goto(-220,0)
t.pendown()
t.forward(90)
t.left(135)
t.forward(90)
t.left(45)
t.forward(90)
t.left(135)
t.forward(90)
t.left(45)
t.end_fill()
t.penup()
screen.bgcolor('gold1')
t.goto(0,200)
t.write("Favorite Sport ", font=("Arial", 24, "bold"), align="center")
turtle.addshape("ball.gif")
t12.shape("ball.gif")
t14.penup()
t14.goto(260,0)
t14.pendown()
turtle.addshape("nfl.gif")
t14.shape("nfl.gif")
turtle.addshape("ball.gif")
t12.penup()
t.penup()
t.goto(0,-200)
t.write("Baseball ", font=("Arial", 24, "bold"), align="center")
t.goto(0,-260)
t.write("Football ", font=("Arial", 24, "bold"), align="center")
turtle.done()